const styles = {
    personalPage: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        height: "100vh",
        backgroundColor: "#f2f2f2",
        fontFamily: "Consolas",
    },
    container: {
        display: "flex",
        flexDirection: "column",
        fontFamily: "Consolas",
        backgroundColor: "#f5f5f5",
        minHeight: "100vh",
        overflowX: "hidden",
        margin: 0,
        padding: 0,
    },
    contentWrapper: {
        display: "flex",
        marginTop: "30px",
        gap: "40px",
        justifyContent: "center",
    },
    leftPanel: {
        backgroundColor: "#fff",
        padding: "30px",
        borderRadius: "10px",
        boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
        minWidth: "300px",
    },
    rightPanel: {
        backgroundColor: "#fff",
        padding: "30px",
        borderRadius: "10px",
        boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
        display: "flex",
        flexDirection: "column",
        gap: "15px",
        minWidth: "250px",
    },
    field: {
        marginBottom: "15px",
        fontSize: "16px",
    },
    actionButton: {
        marginTop: "10px",
        padding: "10px 20px",
        backgroundColor: "#007bff",
        color: "#fff",
        border: "none",
        borderRadius: "6px",
        cursor: "pointer",
    },
    buttonRow: {
        display: "flex",
        gap: "30px",
        marginTop: "20px",
    },
    logoutButton: {
        marginTop: "15px",
        padding: "10px 20px",
        backgroundColor: "#dc3545",
        color: "#fff",
        border: "none",
        borderRadius: "6px",
        cursor: "pointer",
    },
    rightButton: {
        padding: "10px 20px",
        backgroundColor: "#e0e0e0",
        color: "#333",
        border: "none",
        borderRadius: "6px",
        cursor: "pointer",
        textAlign: "left",
    },
};

export default styles;
