const styles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        animation: 'fadeIn 0.3s ease-in-out',
        zIndex: 999,
    },
    modal: {
        background: 'white',
        padding: '30px',
        borderRadius: '10px',
        width: '500px',
        maxHeight: '80vh',
        overflowY: 'auto',
        boxShadow: '0 5px 15px rgba(0,0,0,0.3)',
        animation: 'scaleIn 0.3s ease-in-out',
        position: 'relative',
    },
    closeButton: {
        position: 'absolute',
        top: '10px',
        right: '15px',
        fontSize: '20px',
        background: 'transparent',
        border: 'none',
        cursor: 'pointer',
    },
    list: {
        listStyle: 'none',
        padding: 0,
        margin: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    item: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '10px',
        border: '1px solid #ddd',
        borderRadius: '6px',
        cursor: 'pointer',
        backgroundColor: '#f9f9f9',
    },
    removeBtn: {
        backgroundColor: '#ff4d4f',
        color: 'white',
        border: 'none',
        borderRadius: '50%',
        width: '24px',
        height: '24px',
        cursor: 'pointer',
    },
    addButton: {
        backgroundColor: '#007bff',
        color: 'white',
        padding: '5px 10px',
        border: 'none',
        borderRadius: '6px',
        cursor: 'pointer',
        marginRight: '5px'
    },
    cancelButton: {
        backgroundColor: '#ccc',
        color: '#333',
        padding: '10px 15px',
        border: 'none',
        borderRadius: '6px',
        cursor: 'pointer',
    },
    buttons: {
        display: 'flex',
        gap: '10px',
    },
};

export default styles;
